### ISSUE TITLE
AI Detects Print Head Grill As an Issue

### ISSUE THREAD

**Issue by PDignam** [DrAlexLiu/OctoPrint-PiNozCam#22]
![image](https://github.com/DrAlexLiu/OctoPrint-PiNozCam/assets/4356400/71b9f323-5999-4ac3-a3c7-cd0556328cf8)
The AI consistently detects the Print Head Grill as an issue. Please see image.

**Comment by DrAlexLiu** [comment]
Hi, May I ask where you put your nozzle camera to? It should be under the print head and nozzle, right?

Also, I recommend removing the background things because some will cause false alarms. 

If you use this camera as a camera "targeting the whole printer bed" instead of "under the nozzle", the current AI model is not really designed for this situation, because this AI is tuned more for like finding error print in high-speed blur images. 
If you really want to use a camera "targeting the whole printer bed", I have an AI model, but I am working on compressing it so it can run fast on RPi. It may release soon. 

Also, to solve things like this: 
1. To put the "Failre Scores Threshold" higher than 0.93, like 0.94. But don't set above 0.94. Also, if you put the threshold as high as 0.94, a Pi5 would be necessary because the fast predictions.

**Comment by DrAlexLiu** [comment]
Also, it shows yellow bounding box. It means the plugin does not count it as a real failure. 
Only the failure with the red bounding box will consider it.

**Comment by DrAlexLiu** [comment]
Please use:
https://github.com/DrAlexLiu/OctoPrint-PiNozCam/archive/master.zip. version >=1.0.2

Then, set the parameter like this:
Image Sensitivity：0.02 (0.02-0.04)
Failure Scores Threshold: 0.94 (0.94-0.99)

For failures like this pictures,
Notify Mode Set to: After reaching the Max Failure Count
Max Failure Count: 2 or above

Or use "Set Undetect Zone" to mask it. 

I believe that false alarm, like 2nd picture, would not happen often. But for a real failure, it will send you a lot of messages in a short time.
