### ISSUE TITLE
Flying Bear Ghost 5, false detection

### ISSUE THREAD

**Issue by om2804** [DrAlexLiu/OctoPrint-PiNozCam#24]
Triggers the logo on the table. What can you do about it?

![photo_2024-05-07_10-29-04](https://github.com/DrAlexLiu/OctoPrint-PiNozCam/assets/2576620/8caed040-651d-4a35-9d0e-437b0fe84200)

My settings
![изображение](https://github.com/DrAlexLiu/OctoPrint-PiNozCam/assets/2576620/ed46af52-e190-47d1-988f-e0e364ee2de3)

**Comment by om2804** [comment]
![изображение](https://github.com/DrAlexLiu/OctoPrint-PiNozCam/assets/2576620/44aa0cd1-11ca-4b21-9f65-af5d487baf46)
![изображение](https://github.com/DrAlexLiu/OctoPrint-PiNozCam/assets/2576620/1472d567-4306-4088-a960-701c0e56ecf4)

many false detections

**Comment by om2804** [comment]
> Also, I will release an AI model to design for your situation.

cool, I'll wait

**Comment by DrAlexLiu** [comment]
Thanks. Give me some time. I will let you know the update.

**Comment by DrAlexLiu** [comment]
Please use:
https://github.com/DrAlexLiu/OctoPrint-PiNozCam/archive/master.zip

Then, set the parameter like this:
Image Sensitivity：0.02 (0.02-0.04)
Failure Scores Threshold: 0.94 (0.94-0.99)

For failures like second pictures,
Notify Mode Set to: After reaching the Max Failure Count
Max Failure Count: 2 or above

I believe that false alarm, like 2nd picture, would not happen often. But for a real failure, it will send you a lot of messages in a short time.

**Comment by om2804** [comment]
Thank you, I installed the new version
Doesn't define spaghetti in this case.

![Screenshot_3](https://github.com/DrAlexLiu/OctoPrint-PiNozCam/assets/2576620/06dc7668-61c9-43a5-add1-a64821b3b38a)
![Screenshot_4](https://github.com/DrAlexLiu/OctoPrint-PiNozCam/assets/2576620/2b885f95-5ab5-44f5-ae98-ffb7b9602738)
![Screenshot_2](https://github.com/DrAlexLiu/OctoPrint-PiNozCam/assets/2576620/40a043df-7663-4c6d-85f3-90bdb672c3aa)

**Comment by DrAlexLiu** [comment]
OK. 

In Octoprint, would you please enable the virtual printer? And put the spaghetti on your printing bed. Better to have a desk lamp to provide good light?! I believe your image is a little bit dark. 
![image](https://github.com/DrAlexLiu/OctoPrint-PiNozCam/assets/69814118/b681f8d6-c210-4c55-81b8-38c0e296d069)


Start the virtual print, AI will run, but your printer won't print. Check the AI can detect spaghetti or not?! Also, the AI needs some time to get the spaghetti detect. When Notify Mode Set to: After reaching the Max Failure Count, the AI needs to count 2 speghetti  founds to trigger the message sent. 

Last, may I ask you use pi4 or pi5?

**Comment by DrAlexLiu** [comment]
![image](https://github.com/DrAlexLiu/OctoPrint-PiNozCam/assets/69814118/aaf65c61-0dd3-4bfb-ae5b-a7d8199df0cb)

Thank you for your update. Here is the result by using the AI, the confidence score is 0.78.

1. Would you move your camera higher? Because your camera may not focus on the printing object. It may focus on the closer word "flying bear"? Image with focusing not very well leads the low confidence score. 

I understand you want to lower the camera position, so the camera can see the first several layers. That is the webcam's shortcoming: The object you print is between the narrow space between the nozzle head and printing bed. And the camera is far away to watch this. I would strongly recommend to use NOZZLE camera mode in this case. The nozzle camera is just below the nozzle, and it can find any error immediately. 

2. Would you please move the light in the position like the third and fourth pictures (Counted from top to down in this thread)? It is better to put the light coming from the back of the camera. 

3. May I ask your camera model? Logitech webcam has a very good auto focus. I encourage you use this brand, like C920, if you really do not want to use nozzle camera. 

4. May I ask your pi model? or other pi?  I need to know how fast your Arm CPU is. Thanks. 

You can try to lower your confidence threshold:

Image Sensitivity：0.02 (0.02-0.04)
Failure Scores Threshold: 0.75
Max Failure Count:2
Notify Mode: After reaching the Max Failure Count
Set the undetect zone to put logo and word "flying bear" to black. 

Also, in telegram, you also can manually check your printing status. 
![IMG_0774](https://github.com/DrAlexLiu/OctoPrint-PiNozCam/assets/69814118/9ad84c80-e813-4a65-b64f-c9b10964570d)


Last, a PEI sheet will improve your chance of successful print.
https://3dflyingbear.com/products/flying-bear-pei-plate-for-ghost5

**Comment by DrAlexLiu** [comment]
May I ask what camera do you use now?

**Comment by om2804** [comment]
1 and 2. I will try
3. HBVCAM-F2170HD V22, from aliexpress
4. Orange Pi zero 3

**Comment by DrAlexLiu** [comment]
4. Orange Pi zero 3

Could you return this and buy an Orange pi 3B, RK3566 chip?
My AI model can use RK3566 NPU and its speed is even faster than RPi5 (75 images per minute). It just 30USD, similar price with Orange Pi Zero 3. 

I will release the RKNPU model very soon. 

[Orange Pi 3B 2GB RAM ](https://www.aliexpress.us/item/3256805733488181.html?spm=a2g0o.productlist.main.5.e73d30b4Kp2k0G&algo_pvid=98f4ce45-d56f-4086-ace7-17c554ac9c84&algo_exp_id=98f4ce45-d56f-4086-ace7-17c554ac9c84-2&pdp_npi=4%40dis%21USD%2142.86%2130.00%21%21%2142.86%2130.00%21%402103273e17183044230572284eed75%2112000034855224901%21sea%21US%210%21AB&curPageLogUid=D05SHgbiYUVq&utparam-url=scene%3Asearch%7Cquery_from%3A)

**Comment by om2804** [comment]
> 4. Orange Pi zero 3
> 
> 
> Could you return this and buy an Orange pi 3B, RK3566 chip? My AI model can use RK3566 NPU and its speed is even faster than RPi5 (75 images per minute). It just 30USD, similar price with Orange Pi Zero 3.
> 
> I will release the RKNPU model very soon.
> 
> [Orange Pi 3B 2GB RAM ](https://www.aliexpress.us/item/3256805733488181.html?spm=a2g0o.productlist.main.5.e73d30b4Kp2k0G&algo_pvid=98f4ce45-d56f-4086-ace7-17c554ac9c84&algo_exp_id=98f4ce45-d56f-4086-ace7-17c554ac9c84-2&pdp_npi=4%40dis%21USD%2142.86%2130.00%21%21%2142.86%2130.00%21%402103273e17183044230572284eed75%2112000034855224901%21sea%21US%210%21AB&curPageLogUid=D05SHgbiYUVq&utparam-url=scene%3Asearch%7Cquery_from%3A)

 i can't return it

**Comment by DrAlexLiu** [comment]
Anyway, thank you very much. If you still have any questions related to this, feel free to reopen this.
