### ISSUE TITLE
[Feature Request] Additional notification options.

### ISSUE THREAD

**Issue by trunzoc** [DrAlexLiu/OctoPrint-PiNozCam#9]
So far, this thing is fantastic.  thank you!!!

Would it be possible to add additional notification options other than telegram, even just a generic url/data packet to send to an API?

**Comment by DrAlexLiu** [comment]
which platform do you prefer? Slack? Discord? Or others? Let me know.

**Comment by trunzoc** [comment]
If I had my choice, I'd use Discord.  that's where I send everything else.

Thank you!!!

I've been tweaking the settings to lower false positives and think I have it dialed in.  This is amazing.

**Comment by DrAlexLiu** [comment]
Great. I try to put Discord inside this weekend if I have time. I also try to write a more clear way how to lower the false positive.

**Comment by DrAlexLiu** [comment]
discord notification has been added. 

Please download the latest zip file to install 
https://github.com/DrAlexLiu/OctoPrint-PiNozCam/archive/master.zip

Thanks.

**Comment by DrAlexLiu** [comment]
@trunzoc following up a long time later -- Discord support has come a long way since this was first added. As of 1.1.0 it now has:

- Full button interaction (Check / Mute / Unmute / Pause / Resume / Stop), not just text notifications
- A confirmation step before Pause/Stop actually executes, so a stray click can't cancel a print
- Multi-printer support -- if you run several printers into the same Discord channel, each message is labeled with the printer's name so you can tell them apart

Thanks again for pushing for this back then!
